In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from imutils import paths
import os
import cv2
from skimage import feature

In [3]:
def split(path):
  imgpaths = list(paths.list_images(path))
  data=[]
  labels=[]
  for imgpath in imgpaths:
    label=imgpath.split(os.path.sep)[-2]
    labels.append(label)

    img=cv2.imread(imgpath)
    img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    img=cv2.resize(img,(200,200))

    img=cv2.threshold(img,0,255,cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]

    features = feature.hog(img,orientations=9,pixels_per_cell=(10,10),cells_per_block=(2,2),transform_sqrt=True,block_norm="L1")
    data.append(features)
  return (np.array(data),np.array(labels))


In [4]:
(X_train,y_train)=split(r'C:\Users\Sanjus\Downloads\dataset\dataset\spiral\training')
(X_test,y_test)=split(r'C:\Users\Sanjus\Downloads\dataset\dataset\spiral\testing')

In [5]:
y_train.shape

(72,)

In [6]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()

In [7]:
y_train=enc.fit_transform(y_train)

y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [8]:
y_test=enc.fit_transform(y_test)

y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [9]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [10]:
preds=classifier.predict(X_test)

In [11]:
preds

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1], dtype=int64)

In [12]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,preds)

0.8

In [13]:
from sklearn import metrics
metrics.confusion_matrix(y_test,preds)

array([[13,  2],
       [ 4, 11]], dtype=int64)

In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.76      0.87      0.81        15
           1       0.85      0.73      0.79        15

    accuracy                           0.80        30
   macro avg       0.81      0.80      0.80        30
weighted avg       0.81      0.80      0.80        30



In [15]:
import pickle
pickle.dump(classifier,open('model.pkl','wb'))